package com.shiftsync.domain.entity;

import com.shiftsync.domain.enums.ShiftStatus;
import com.shiftsync.domain.enums.ShiftType;
import com.shiftsync.domain.enums.Skill;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import lombok.*;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Hospital shift requirement or assignment.
 */
@Entity
@Table(name = "shifts")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Shift {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotNull
    @Column(nullable = false)
    private LocalDate shiftDate;

    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private ShiftType shiftType;

    @NotNull
    @ManyToOne(fetch = FetchType.EAGER, optional = false)
    @JoinColumn(name = "department_id", nullable = false)
    private Department department;

    /**
     * Healthcare worker assigned to this shift. Null when the shift slot is unassigned.
     */
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "employee_id")
    private Employee assignedEmployee;

    /**
     * Optional specific clinical skill required for this individual slot.
     */
    @Enumerated(EnumType.STRING)
    private Skill requiredSkill;

    @NotNull
    @Builder.Default
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private ShiftStatus status = ShiftStatus.UNASSIGNED;

    /**
     * Start timestamp of this shift based on calendar date and shift window.
     */
    public LocalDateTime getStartDateTime() {
        return shiftType != null && shiftDate != null ? shiftType.getStartDateTime(shiftDate) : null;
    }

    /**
     * End timestamp of this shift, properly handling night shifts that cross midnight.
     */
    public LocalDateTime getEndDateTime() {
        return shiftType != null && shiftDate != null ? shiftType.getEndDateTime(shiftDate) : null;
    }

    /**
     * Duration of the shift in hours.
     */
    public double getDurationHours() {
        return shiftType != null ? shiftType.getDurationHours() : 0.0;
    }

    /**
     * Checks if this shift takes place in a high-stress ward (e.g. ICU, ER).
     */
    public boolean isHighStress() {
        return department != null && department.isHighStress();
    }

    /**
     * Calculates the cognitive load generated by this shift.
     * Formula: Duration * Department Stress Multiplier * Circadian Disruption Weight * Employee Fatigue Factor
     */
    public double calculateCognitiveLoadScore() {
        if (shiftType == null || department == null) {
            return 0.0;
        }
        double baseDuration = shiftType.getDurationHours();
        double stress = department.getStressMultiplier();
        double circadian = shiftType.getCircadianDisruptionWeight();
        double fatigue = (assignedEmployee != null) ? assignedEmployee.getCurrentFatigueFactor() : 1.0;

        return baseDuration * stress * circadian * fatigue;
    }
}
